------------------------
-- application schema --
------------------------
DROP TABLE IF EXISTS ex_order;

CREATE TABLE ex_order (
	id VARCHAR(36) PRIMARY KEY
) ENGINE=InnoDB;

-------------------------------
-- spring integration schema --
-------------------------------
DROP TABLE IF EXISTS INT_MESSAGE;
DROP TABLE IF EXISTS INT_MESSAGE_GROUP;
DROP TABLE IF EXISTS INT_GROUP_TO_MESSAGE;
-- DROP INDEX IF EXISTS INT_MESSAGE_IX1;

CREATE TABLE INT_MESSAGE  (
	MESSAGE_ID CHAR(36),
	REGION VARCHAR(100),
	CREATED_DATE DATETIME NOT NULL,
	MESSAGE_BYTES BLOB,
	constraint MESSAGE_PK primary key (MESSAGE_ID, REGION)
) ENGINE=InnoDB;

CREATE INDEX INT_MESSAGE_IX1 ON INT_MESSAGE (CREATED_DATE);

CREATE TABLE INT_GROUP_TO_MESSAGE  (
	GROUP_KEY CHAR(36),
	MESSAGE_ID CHAR(36),
	REGION VARCHAR(100),
	constraint GROUP_TO_MESSAG_PK primary key (GROUP_KEY, MESSAGE_ID, REGION)
) ENGINE=InnoDB;

CREATE TABLE INT_MESSAGE_GROUP  (
	GROUP_KEY CHAR(36),
	REGION VARCHAR(100),
	MARKED BIGINT,
	COMPLETE BIGINT,
	LAST_RELEASED_SEQUENCE BIGINT,
	CREATED_DATE DATETIME NOT NULL,
	UPDATED_DATE DATETIME DEFAULT NULL,
	constraint MESSAGE_GROUP_PK primary key (GROUP_KEY, REGION)
) ENGINE=InnoDB;